# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Yuhang He
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "" # the subpath of the site
url: "https://gehenhe.github.io" # the base hostname & protocol for the site
# og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Publication
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: hyh1379478@163.com
      link: mailto:hyh1379478@163.com

  follow:
    - name: GitHub
      link: https://github.com/GehenHe
    - name: Scholar
      link: https://scholar.google.com.hk/citations?user=9VCIiVcAAAAJ&hl=zh-CN&oi=ao

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
